export const STACK_ICON_SLUGS: Record<string, string> = {
  TypeScript: "typescript",
  JavaScript: "javascript",
  Python: "python",
  React: "react",
  "Next.js": "nextdotjs",
  "Node.js": "nodedotjs",
  Electron: "electron",
  "Tailwind CSS": "tailwindcss",
  "Tailwind": "tailwindcss",
  Expo: "expo",
  "React Native": "react",
  Gradio: "gradio",
  Supabase: "supabase",
  "Supabase Realtime": "supabase",
  "Supabase pgvector": "supabase",
  Firebase: "firebase",
  PostgreSQL: "postgresql",
  Docker: "docker",
  Vercel: "vercel",
  "Three.js": "threedotjs",
  "Rapier.js": "rust",
  PWA: "pwa",
  "nut-js": "nutanix",
  Vosk: "vosk",
  Picovoice: "picovoice",
  "AI APIs": "openai",
  "Kaggle VLM": "kaggle",
  Concept: "lightbulb",
  Gamma: "gamma",
  "Stitch prototype": "figma",
  "Browser Automation": "googlechrome",
  "Multiple LLMs": "openai",
  "Local AI": "ollama",
  Desktop: "electron",
}

export function getStackIconSlug(tech: string): string {
  return STACK_ICON_SLUGS[tech] ?? tech.toLowerCase().replace(/\s+/g, "")
}
